- name: geerlingguy.mysql
- name: ANXS.postgresql
- name: geerlingguy.redis
- name: geerlingguy.php
- name: geerlingguy.php-versions
- name: geerlingguy.composer
- name: geerlingguy.pip
- name: geerlingguy.supervisor
- name: geerlingguy.nginx

- name: 'laravel-deploy' 
  src: 'https://projects.ronasit.com/ansible/laravel.git'
  scm: 'git'
  version: 'ubuntu-20'
